/*
 * Constantes / ActionTypes
 */

// CART ACTIONS
export const cartActionApp = {
  ADD_ITEM: 'CART_ADD_ITEM',
  SET_CART_TOGGLE_STATUS: 'CART_SET_TOGGLE_STATUS',
  ADD_ITEM_BY_SKU: 'CART_ADD_ITEM_BY_SKU',
  REMOVE_ITEM_BY_SKU: 'CART_REMOVE_ITEM_BY_SKU',
  REMOVE_ALL_BY_SKU: 'REMOVE_ALL_BY_SKU'
}
