/*
 * Constantes / ActionTypes
 */

// PRODUCT ACTIONS
export const productionActionTypes = {
  SET_PRODUCTS: 'PRODUCTS_SET_PRODUCTS',
  SET_PAGE_PRODUCT: 'SET_PAGE_PRODUCT',
  PRODUCTS_SET_MODAL_PRODUCT: 'PRODUCTS_SET_MODAL_PRODUCT',
};
